version: '3.1'

services:

  db:
    image: mysql:8.3 #use version 8.3. See https://hub.docker.com/layers/library/mysql/8.3/images/sha256-eeabfa5cd6a2091bf35eb9eae6ae48aab8231fd760f5a61cd0129df454333b1d?context=explore for more information about this version
    # command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: supersecurepassword
    volumes:
      - ./mysql:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db

volumes:
  mysql: